/**
 * Builds the Code Connect status snapshot the docs page renders:
 *   apps/docs/app/code-connect/mappings.generated.ts
 *
 * Two-stage pipeline (Figma's Code Connect has no public REST read endpoint, and
 * `get_code_connect_map` is an MCP tool — not callable from a headless build):
 *
 *   1. FETCH (MCP, run in an MCP-enabled session): for each set node in MANIFEST,
 *      call `get_code_connect_map` and write the normalized result into
 *      `code-connect-map.json` ({ map: { [setNode]: [{componentName, source}] } }).
 *   2. BUILD (this script, pure Node / CI-friendly): cross-reference that map with
 *      MANIFEST and emit the generated statuses.
 *
 * A Figma set counts as `connected` when the fetched map for its node contains a
 * mapping to the EXPECTED component+source (so a Button Group whose only mapped
 * descendants are child Buttons is still `pending`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const mapPath = join(here, "code-connect-map.json");
const outPath = join(here, "..", "app", "code-connect", "mappings.generated.ts");

const BUTTON = "packages/ui/src/components/button.tsx";
const GROUP = "packages/ui/src/components/button-group.tsx";
const CTA = "packages/ui/src/components/cta.tsx";
const CHECKBOX = "packages/ui/src/components/checkbox.tsx";

/** The mappings we intend to exist — the "what should be connected" list. */
const MANIFEST = [
  { component: "Button", source: BUTTON, figmaSet: "[Button] Page", nodeId: "654:107975" },
  { component: "Button", source: BUTTON, figmaSet: "[Button] Module", nodeId: "654:108042" },
  { component: "Button", source: BUTTON, figmaSet: "[Button] Inline", nodeId: "654:108197" },
  { component: "ButtonGroup", source: GROUP, figmaSet: "[Button Group] CTA", nodeId: "17892:404602" },
  { component: "ButtonGroup", source: GROUP, figmaSet: "[Button Group] Bottom Sheet", nodeId: "654:108885" },
  { component: "ButtonGroup", source: GROUP, figmaSet: "[Button Group] Dialog", nodeId: "654:108897" },
  { component: "ButtonGroup", source: GROUP, figmaSet: "[Button Group] Card", nodeId: "654:108906" },
  { component: "Cta", source: CTA, figmaSet: "[CTA]", nodeId: "14942:51398" },
  { component: "Checkbox", source: CHECKBOX, figmaSet: "[Checkbox]", nodeId: "654:107836" },
];

type MapEntry = { componentName: string; source: string };
const { map } = JSON.parse(readFileSync(mapPath, "utf8")) as {
  map: Record<string, MapEntry[]>;
};

const rows = MANIFEST.map((m) => {
  const entries = map[m.nodeId] ?? [];
  const connected = entries.some(
    (e: MapEntry) => e.componentName === m.component && e.source === m.source
  );
  return { ...m, status: connected ? "connected" : "pending" };
});

const connectedCount = rows.filter((r) => r.status === "connected").length;

const banner = "// AUTO-GENERATED by apps/docs/scripts/build-code-connect.ts — do not edit by hand.";
const body = `${banner}
// Refresh: re-run the MCP fetch (get_code_connect_map → code-connect-map.json),
// then \`node apps/docs/scripts/build-code-connect.ts\`.

export type CcStatus = "connected" | "pending";

export type CcMapping = {
  component: string;
  source: string;
  figmaSet: string;
  nodeId: string;
  status: CcStatus;
};

export const GENERATED_AT = ${JSON.stringify(new Date().toISOString())};

export const MAPPINGS: CcMapping[] = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync(outPath, body);
console.log(`✓ mappings.generated.ts (${connectedCount}/${rows.length} connected)`);
