/**
 * Generates `dist/theme.css` from the token source.
 *
 * Emits (Tailwind v4 convention):
 *   :root {              — every token as a CSS custom property (Figma-1:1 names)
 *     --color-*  --radius-*  --spacing-*  --font-size-*  --font-sans  --font-weight-*
 *   }
 *   @theme inline {       — registers color + radius tokens as Tailwind utilities
 *     --color-container-brand-primary: var(--color-container-brand-primary);  → bg-container-brand-primary
 *     --radius-medium: var(--radius-medium);                                  → rounded-medium
 *   }
 *
 * Spacing / font-size stay as raw custom properties (usable via var()); wiring
 * them into Tailwind utilities is a later refinement.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { color, radius, spacing, fontSize, font } from "../src/tokens.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "dist");

const block = (entries: [string, string][], prefix: string) =>
  entries.map(([k, v]) => `  --${prefix}-${k}: ${v};`).join("\n");

const rootVars = [
  block(Object.entries(color), "color"),
  block(Object.entries(radius), "radius"),
  block(Object.entries(spacing), "spacing"),
  block(Object.entries(fontSize), "font-size"),
  `  --font-sans: ${font.sans};`,
  `  --font-weight-base: ${font.weightBase};`,
  `  --font-weight-strong: ${font.weightStrong};`,
].join("\n");

const themeMap = [
  // colors → bg-*/text-*/border-*/ring-*
  Object.keys(color)
    .map((k) => `  --color-${k}: var(--color-${k});`)
    .join("\n"),
  // radius → rounded-*
  Object.keys(radius)
    .map((k) => `  --radius-${k}: var(--radius-${k});`)
    .join("\n"),
  // spacing → p-*/px-*/py-*/gap-*/m-*/size-* (Figma-1:1 keys)
  Object.keys(spacing)
    .map((k) => `  --spacing-${k}: var(--spacing-${k});`)
    .join("\n"),
  // font sizes → text-* (Tailwind reads the --text-* namespace)
  Object.keys(fontSize)
    .map((k) => `  --text-${k}: var(--font-size-${k});`)
    .join("\n"),
  // font weights → font-base / font-strong
  `  --font-weight-base: var(--font-weight-base);`,
  `  --font-weight-strong: var(--font-weight-strong);`,
  // font family → font-sans
  `  --font-sans: var(--font-sans);`,
].join("\n");

const css = `/* AUTO-GENERATED by @uds/tokens — do not edit. Run \`pnpm --filter @uds/tokens build\`. */
/* Source: Figma "Core Foundation v1.0.0" (CzlSHJumy6SGUMdTIvSjq8) — LIGHT mode. */

:root {
${rootVars}
}

@theme inline {
${themeMap}
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "theme.css"), css, "utf8");
console.log(`✓ @uds/tokens → dist/theme.css (${Object.keys(color).length} colors)`);
