// AUTO-GENERATED by apps/docs/scripts/build-code-connect.ts — do not edit by hand.
// Refresh: re-run the MCP fetch (get_code_connect_map → code-connect-map.json),
// then `node apps/docs/scripts/build-code-connect.ts`.

export type CcStatus = "connected" | "pending";

export type CcMapping = {
  component: string;
  source: string;
  figmaSet: string;
  nodeId: string;
  status: CcStatus;
};

export const GENERATED_AT = "2026-09-03T06:35:45.852Z";

export const MAPPINGS: CcMapping[] = [
  {
    "component": "Button",
    "source": "packages/ui/src/components/button.tsx",
    "figmaSet": "[Button] Page",
    "nodeId": "654:107975",
    "status": "connected"
  },
  {
    "component": "Button",
    "source": "packages/ui/src/components/button.tsx",
    "figmaSet": "[Button] Module",
    "nodeId": "654:108042",
    "status": "connected"
  },
  {
    "component": "Button",
    "source": "packages/ui/src/components/button.tsx",
    "figmaSet": "[Button] Inline",
    "nodeId": "654:108197",
    "status": "connected"
  },
  {
    "component": "ButtonGroup",
    "source": "packages/ui/src/components/button-group.tsx",
    "figmaSet": "[Button Group] CTA",
    "nodeId": "17892:404602",
    "status": "connected"
  },
  {
    "component": "ButtonGroup",
    "source": "packages/ui/src/components/button-group.tsx",
    "figmaSet": "[Button Group] Bottom Sheet",
    "nodeId": "654:108885",
    "status": "connected"
  },
  {
    "component": "ButtonGroup",
    "source": "packages/ui/src/components/button-group.tsx",
    "figmaSet": "[Button Group] Dialog",
    "nodeId": "654:108897",
    "status": "connected"
  },
  {
    "component": "ButtonGroup",
    "source": "packages/ui/src/components/button-group.tsx",
    "figmaSet": "[Button Group] Card",
    "nodeId": "654:108906",
    "status": "connected"
  },
  {
    "component": "Cta",
    "source": "packages/ui/src/components/cta.tsx",
    "figmaSet": "[CTA]",
    "nodeId": "14942:51398",
    "status": "connected"
  },
  {
    "component": "Checkbox",
    "source": "packages/ui/src/components/checkbox.tsx",
    "figmaSet": "[Checkbox]",
    "nodeId": "654:107836",
    "status": "connected"
  },
  {
    "component": "TextField",
    "source": "packages/ui/src/components/text-field.tsx",
    "figmaSet": "[Text Field] Text",
    "nodeId": "2230:35899",
    "status": "connected"
  }
];
